name: Docker Image CI/CD

on:
  push:
    branches:
      - main  # Déclenchement sur les pushs vers la branche main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t my-docker-image .

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Tag Docker image
      run: |
        docker tag my-docker-image:latest ghcr.io/${{ github.repository_owner }}/my-docker-image:Dockerfile
        docker tag my-docker-image:latest ghcr.io/${{ github.repository_owner }}/my-docker-image:latest

    - name: Push Docker image to GitHub Container Registry
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/my-docker-image:Dockerfile
        docker push ghcr.io/${{ github.repository_owner }}/my-docker-image:latest
